# Generated by Django 6.0.2 on 2026-03-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingreso',
            new_name='ingresos_in_negocio_a4a61e_idx',
            old_name='ingresos_ing_negocio_3d2dcf_idx',
        ),
        migrations.RenameIndex(
            model_name='ingreso',
            new_name='ingresos_in_negocio_c0a257_idx',
            old_name='ingresos_ing_negocio_381ef6_idx',
        ),
    ]
