# Generated by Django 6.0.2 on 2026-03-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_productoingreso_detalle_producto_and_more'),
        ('ingresos', '0002_rename_ingresos_ing_negocio_3d2dcf_idx_ingresos_in_negocio_a4a61e_idx_and_more'),
    ]

    operations = [
    ]
