# Generated by Django 6.0.2 on 2026-02-06 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_NEGOCIOS',
            fields=[
                ('id_negocio', models.BigAutoField(db_column='ID_NEGOCIO', primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(db_column='NOMBRE_COMERCIAL', max_length=150)),
                ('provincia', models.CharField(blank=True, db_column='PROVINCIA', max_length=60, null=True)),
                ('moneda_base', models.CharField(db_column='MONEDA_BASE', default='CRC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'cnt"."TB_NEGOCIOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TB_CONFIG_FISCAL_NEGOCIO',
            fields=[
                ('id_config_fiscal', models.BigAutoField(db_column='ID_CONFIG_FISCAL', primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(blank=True, db_column='TIPO_IDENTIFICACION', max_length=20, null=True)),
                ('identificacion', models.CharField(blank=True, db_column='IDENTIFICACION', max_length=30, null=True)),
                ('regimen_iva', models.CharField(blank=True, db_column='REGIMEN_IVA', max_length=50, null=True)),
                ('aplica_iva', models.BooleanField(db_column='APLICA_IVA', default=True)),
                ('porc_iva', models.DecimalField(blank=True, db_column='PORC_IVA', decimal_places=2, max_digits=5, null=True)),
                ('periodo_iva', models.CharField(db_column='PERIODO_IVA', default='MENSUAL', max_length=20)),
                ('declara_renta', models.BooleanField(db_column='DECLARA_RENTA', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('negocio', models.OneToOneField(db_column='ID_NEGOCIO', on_delete=django.db.models.deletion.CASCADE, related_name='config_fiscal', to='accounts.tb_negocios')),
            ],
            options={
                'db_table': 'cnt"."TB_CONFIG_FISCAL_NEGOCIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TB_USUARIOS_APP',
            fields=[
                ('id_usuario_app', models.BigAutoField(db_column='ID_USUARIO_APP', primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=30, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FECHA_REGISTRO')),
                ('user', models.OneToOneField(db_column='ID_AUTH_USER', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_app', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cnt"."TB_USUARIOS_APP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TB_USUARIO_NEGOCIO',
            fields=[
                ('id_usuario_negocio', models.BigAutoField(db_column='ID_USUARIO_NEGOCIO', primary_key=True, serialize=False)),
                ('rol_en_negocio', models.CharField(db_column='ROL_EN_NEGOCIO', default='OWNER', max_length=50)),
                ('negocio', models.ForeignKey(db_column='ID_NEGOCIO', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='accounts.tb_negocios')),
                ('user', models.ForeignKey(db_column='ID_AUTH_USER', on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cnt"."TB_USUARIO_NEGOCIO',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('user', 'negocio'), name='UK_USER_NEG')],
            },
        ),
    ]
