# Generated by Django 6.0.2 on 2026-02-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_negocios',
            name='moneda_base',
            field=models.CharField(choices=[('CRC', 'Colones (CRC)'), ('USD', 'Dólares (USD)')], db_column='MONEDA_BASE', default='CRC', max_length=10),
        ),
        migrations.AlterField(
            model_name='tb_negocios',
            name='provincia',
            field=models.CharField(choices=[('SJO', 'San José (SJO)'), ('ALJ', 'Alajuela (ALJ)'), ('HER', 'Heredia (HER)'), ('GUA', 'Guanacaste (GUA)'), ('CAR', 'Cartago (CAR)'), ('PUN', 'Puntarenas (PUN)'), ('LIM', 'Limón (LIM)')], db_column='PROVINCIA', default='SJO', max_length=20),
        ),
    ]
