# Generated by Django 6.0.2 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=150)),
                ("identificacion", models.CharField(max_length=30, unique=True)),
                ("correo_electronico", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=25)),
                ("direccion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tb_sgc_clientes",
                "ordering": ["nombre"],
            },
        ),
    ]
