# Generated by Django 6.0.2 on 2026-03-10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_tb_negocios_moneda_base_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CierreFiscalPeriodo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("MENSUAL", "Mensual"), ("ANUAL", "Anual")], default="MENSUAL", max_length=10)),
                ("anio", models.PositiveIntegerField()),
                ("mes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("estado", models.CharField(choices=[("BORRADOR", "Borrador"), ("CERRADO", "Cerrado")], default="BORRADOR", max_length=10)),
                ("compras_gravadas", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("compras_exentas", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("credito_fiscal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("ventas_gravadas", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("ventas_exentas", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("debito_fiscal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("iva_por_pagar", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("utilidad_proyectada", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("impuesto_renta_proyectado", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("observaciones", models.TextField(blank=True)),
                ("cerrado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "negocio",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cierres_fiscales", to="accounts.tb_negocios"),
                ),
            ],
            options={
                "ordering": ["-anio", "-mes", "tipo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("negocio", "tipo", "anio", "mes"),
                        name="uq_cierre_fiscal_negocio_tipo_anio_mes",
                    )
                ],
            },
        ),
    ]
