# Generated by Django 6.0.2 on 2026-02-10 04:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_tb_negocios_moneda_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_gasto', to='accounts.tb_negocios')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigCorreoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=120)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_ssl', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=200)),
                ('carpeta', models.CharField(default='INBOX', max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correo_facturas', to='accounts.tb_negocios')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=150)),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validada', 'Validada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='facturas_gastos/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='facturas_gastos/pdf/')),
                ('origen', models.CharField(default='correo', max_length=20)),
                ('email_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.categoriagasto')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='accounts.tb_negocios')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['negocio', 'estado'], name='gastos_fact_negocio_4c1d7c_idx'), models.Index(fields=['negocio', 'numero_factura'], name='gastos_fact_negocio_fef4c1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email_message_id__isnull', False)), fields=('negocio', 'email_message_id'), name='uniq_factura_por_mensaje')],
            },
        ),
    ]
