# Generated by Django 6.0.2 on 2026-02-12 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tb_negocios_moneda_base_and_more'),
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturagasto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_registro', 'En registro'), ('registrada', 'Registrada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField()),
                ('metodo_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gasto', to='gastos.facturagasto')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='accounts.tb_negocios')),
            ],
            options={
                'indexes': [models.Index(fields=['negocio', 'fecha_gasto'], name='gastos_gast_negocio_01ac9c_idx')],
            },
        ),
    ]
