# Generated by Django 6.0.2 on 2026-02-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_facturagasto_estado_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
