# Generated by Django 6.0.2 on 2026-02-13 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tb_negocios_moneda_base_and_more'),
        ('gastos', '0003_gasto_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='activo',
        ),
        migrations.AddField(
            model_name='facturagasto',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('anulado', 'Anulado')], default='registrado', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['negocio', 'estado'], name='gastos_gast_negocio_e89ecc_idx'),
        ),
    ]
