# Generated by Django 6.0.2 on 2026-02-13 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tb_negocios_moneda_base_and_more'),
        ('gastos', '0004_remove_gasto_activo_facturagasto_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('proveedor_match', models.CharField(help_text='Texto que debe contener el proveedor (case-insensitive)', max_length=150)),
                ('numero_factura_prefijo', models.CharField(blank=True, help_text='Opcional: prefijo del número de factura', max_length=50, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('auto_registrar', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_fijos', to='accounts.tb_negocios')),
            ],
            options={
                'indexes': [models.Index(fields=['negocio', 'activo'], name='gastos_gast_negocio_231c46_idx'), models.Index(fields=['negocio', 'proveedor_match'], name='gastos_gast_negocio_e87a5b_idx')],
            },
        ),
    ]
