# Generated by Django 6.0.2 on 2026-03-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_configcorreofactura_multi_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configcorreofactura',
            options={'ordering': ['-created_at']},
        ),
    ]
