# Generated by Django 6.0.2 on 2026-03-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_alter_configcorreofactura_options'),
        ('gastos', '0007_facturagasto_moneda_alertas_tipo_xml'),
    ]

    operations = [
    ]
