# Generated by Django 6.0.2 on 2026-03-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_gasto_campos_contables'),
        ('gastos', '0008_merge_20260307_1620'),
    ]

    operations = [
    ]
