# Generated by Django 6.0.2 on 2026-03-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_proveedorgasto_facturagasto_proveedor_registrado'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proveedorgasto',
            new_name='gastos_prov_negocio_6b03c6_idx',
            old_name='gastos_prove_negocio_0f5de1_idx',
        ),
        migrations.RenameIndex(
            model_name='proveedorgasto',
            new_name='gastos_prov_negocio_68bb7b_idx',
            old_name='gastos_prove_negocio_50860c_idx',
        ),
    ]
