# Generated by Django 6.0.2 on 2026-03-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_facturagasto_campos_proveedor_xml'),
        ('gastos', '0011_rename_gastos_prove_negocio_0f5de1_idx_gastos_prov_negocio_6b03c6_idx_and_more'),
    ]

    operations = [
    ]
