# Generated by Django 6.0.2 on 2026-03-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='existencia',
            new_name='ventas_exis_almacen_09573c_idx',
            old_name='ventas_exis_almacen_8a1e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='facturaventa',
            new_name='ventas_fact_negocio_8e8b6d_idx',
            old_name='ventas_fact_negocio_97f58c_idx',
        ),
        migrations.RenameIndex(
            model_name='facturaventa',
            new_name='ventas_fact_negocio_697b39_idx',
            old_name='ventas_fact_negocio_16d8a7_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoinventario',
            new_name='ventas_movi_negocio_e4a05b_idx',
            old_name='ventas_movi_negocio_59e900_idx',
        ),
    ]
