# Generated by Django 6.0 on 2026-01-12 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('contratista', models.CharField(max_length=255, verbose_name='Contratista')),
                ('gerencia', models.CharField(max_length=120, verbose_name='Gerencia')),
                ('objeto', models.TextField(verbose_name='Objeto del contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto (₡)')),
                ('tipo', models.CharField(choices=[('BIENES', 'Bienes'), ('SERVICIOS', 'Servicios'), ('CONSULTORIA', 'Consultoría')], default='BIENES', max_length=20, verbose_name='Tipo de contrato')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PRORROGA', 'En prórroga'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Condiciones / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'TB_SGC_CONTRATOS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='contratos/documentos/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Documento de contrato',
                'verbose_name_plural': 'Documentos de contrato',
                'db_table': 'TB_SGC_CONTRATOS_DOCUMENTOS',
                'ordering': ['-subido_en'],
            },
        ),
    ]
